/**
 * NIST-developed software is provided by NIST as a public service. You may
 * use, copy and distribute copies of the software in any medium, provided that
 * you keep intact this entire notice. You may improve, modify and create
 * derivative works of the software or any portion of the software, and you may
 * copy and distribute such modifications or works. Modified works should carry
 * a notice stating that you changed the software and should note the date and
 * nature of any such change. Please explicitly acknowledge the National
 * Institute of Standards and Technology as the source of the software.
 *
 * NIST-developed software is expressly provided "AS IS." NIST MAKES NO
 * WARRANTY OF ANY KIND, EXPRESS, IMPLIED, IN FACT OR ARISING BY OPERATION OF
 * LAW, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTY OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT AND DATA ACCURACY. NIST
 * NEITHER REPRESENTS NOR WARRANTS THAT THE OPERATION OF THE SOFTWARE WILL BE
 * UNINTERRUPTED OR ERROR-FREE, OR THAT ANY DEFECTS WILL BE CORRECTED. NIST
 * DOES NOT WARRANT OR MAKE ANY REPRESENTATIONS REGARDING THE USE OF THE
 * SOFTWARE OR THE RESULTS THEREOF, INCLUDING BUT NOT LIMITED TO THE
 * CORRECTNESS, ACCURACY, RELIABILITY, OR USEFULNESS OF THE SOFTWARE.
 *
 * You are solely responsible for determining the appropriateness of using and
 * distributing the software and you assume all risks associated with its use,
 * including but not limited to the risks and costs of program errors,
 * compliance with applicable laws, damage to or loss of data, programs or
 * equipment, and the unavailability or interruption of operation. This
 * software is not intended to be used in any situation where a failure could
 * cause risk of injury or damage to property. The software developed by NIST
 * employees is not subject to copyright protection within the United States.
 */

#ifndef ORAN_LM_NR_2_NR_RSRP_LAG_ONNX_HANDOVER_H
#define ORAN_LM_NR_2_NR_RSRP_LAG_ONNX_HANDOVER_H

#include "oran-data-repository.h"
#include "oran-lm.h"

#include <onnxruntime_cxx_api.h>

#include <deque>
#include <map>
#include <string>
#include <vector>

namespace ns3
{

/**
 * @ingroup oran
 *
 * Logic Module for the Near-RT RIC that issues NR-to-NR handover Commands from
 * an ONNX model whose features are the serving-to-neighbour RSRP difference
 * and a window of its own recent history.
 *
 * The feature vector, in this order, is
 *
 *     [ d(t), d(t-1), d(t-2), ..., d(t-NumLags) ]
 *
 * with d = RSRP(best neighbour) - RSRP(serving), in dB and SIGNED, so that a
 * positive value means the neighbour is the stronger cell. This matches the
 * training convention in examples/vienna_ho_rf_lag.py; reversing it would
 * silently invert the model.
 *
 * THE LAG SPACING IS ONE LOGIC MODULE QUERY, NOT A FIXED TIME. One sample is
 * appended per Run(), so the features are spaced by the Near-RT RIC's
 * LmQueryInterval. The shipped model was trained on 0.1 s samples, so the RIC
 * must be configured with LmQueryInterval = 100 ms for the features to mean
 * what the model was fitted on. Running the RIC faster or slower silently
 * rescales the history window and degrades the model rather than failing.
 *
 * The model is expected to expose two outputs, a label and a probability
 * tensor of shape [N, 2], which is what skl2onnx produces when ZipMap is
 * disabled. The Command is issued when the probability of class 1 exceeds
 * DecisionThreshold, so the operating point can be moved without re-exporting.
 *
 * @see OranLmNr2NrRsrpSinrOnnxHandover for the two-feature, no-history variant.
 */
class OranLmNr2NrRsrpLagOnnxHandover : public OranLm
{
  protected:
    /** Per-UE information gathered from the Data Repository. */
    struct UeInfo
    {
        uint64_t nodeId; //!< The E2 node ID.
        uint16_t cellId; //!< The serving cell ID.
        uint16_t rnti;   //!< The RNTI.
    };

    /** Per-gNB information gathered from the Data Repository. */
    struct GnbInfo
    {
        uint64_t nodeId; //!< The E2 node ID.
        uint16_t cellId; //!< The cell ID.
    };

  public:
    /**
     * Gets the TypeId of the OranLmNr2NrRsrpLagOnnxHandover class.
     *
     * @return The TypeId.
     */
    static TypeId GetTypeId();

    /** Constructor of the OranLmNr2NrRsrpLagOnnxHandover class. */
    OranLmNr2NrRsrpLagOnnxHandover();

    /** Destructor of the OranLmNr2NrRsrpLagOnnxHandover class. */
    ~OranLmNr2NrRsrpLagOnnxHandover() override;

    /**
     * Runs the ML model over each registered NR UE and returns the handover
     * Commands it recommends.
     *
     * @return The Commands generated by this Logic Module.
     */
    std::vector<Ptr<OranCommand>> Run() override;

    /**
     * Opens the ONNX model and creates the inference session.
     *
     * @param onnxModelPath The file path of the ONNX model.
     */
    void SetOnnxModelPath(const std::string& onnxModelPath);

  private:
    /**
     * Collects the cell and RNTI of every registered NR UE.
     *
     * @param data The Data Repository.
     * @return The collected UE information.
     */
    std::vector<UeInfo> GetUeInfos(Ptr<OranDataRepository> data) const;

    /**
     * Collects the cell ID of every registered NR gNB.
     *
     * @param data The Data Repository.
     * @return The collected gNB information.
     */
    std::vector<GnbInfo> GetGnbInfos(Ptr<OranDataRepository> data) const;

    /**
     * Evaluates the model for one UE and returns a handover Command if it
     * recommends one.
     *
     * @param data The Data Repository.
     * @param ueInfo The UE to evaluate.
     * @param gnbInfos The registered gNBs, used to resolve the serving E2 node.
     * @return The Command, or nullptr.
     */
    Ptr<OranCommand> EvaluateUe(Ptr<OranDataRepository> data,
                                const UeInfo& ueInfo,
                                const std::vector<GnbInfo>& gnbInfos);

    Ort::Env m_env;                  //!< The ONNX Runtime environment.
    Ort::Session m_session{nullptr}; //!< The ONNX inference session.
    /// CPU memory descriptor for the input tensor.
    Ort::MemoryInfo m_memoryInfo{Ort::MemoryInfo::CreateCpu(OrtDeviceAllocator, OrtMemTypeCPU)};
    Ort::AllocatorWithDefaultOptions m_allocator; //!< The ONNX allocator.

    uint32_t m_numLags;         //!< Number of lagged differences in the feature vector.
    double m_decisionThreshold; //!< Probability of class 1 above which a handover is issued.

    /// Recent RSRP differences per UE, most recent first.
    std::map<uint64_t, std::deque<double>> m_diffHistory;

}; // class OranLmNr2NrRsrpLagOnnxHandover

} // namespace ns3

#endif /* ORAN_LM_NR_2_NR_RSRP_LAG_ONNX_HANDOVER_H */
