# -*- coding: utf-8 -*-
"""NR_LTE_RSRP_Statistical_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VOzSs1qrMkQi7yrNP_BvVjd6fDS4VcLU

## Loading Packages
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import SMOTE

from sklearn.metrics import roc_curve, roc_auc_score

"""## Loading Data"""

df = pd.read_csv("../../../vienna-ho-331-286-metrics.csv")

df.shape

print('Columns of df:')
print(df.columns)

X = df.drop(columns=["ho_command_issued", "sim_time_s", "serving_pci"])
y = df["ho_command_issued"]

X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.2, random_state=2)

# for i in range(500):
#   X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.2, random_state=i)
#   t = Y_train.value_counts().reset_index()
#   if t[t["ho_command_issued"] == 1]["count"].item() == 2:
#     print(i)

Y_train.value_counts()

smote_training = SMOTE(random_state=42, k_neighbors=1)
smote_testing = SMOTE(random_state=42, k_neighbors=1)

X_train, Y_train = smote_training.fit_resample(X_train, Y_train)
X_test, Y_test = smote_testing.fit_resample(X_test, Y_test)

X_train["rsrp_diff"] = X_train["rsrp_serving_dbm"] - X_train["rsrp_neighbor_286_dbm"]

X_train.drop(columns=["rsrp_serving_dbm", "rsrp_neighbor_286_dbm"], inplace=True)

X_test["rsrp_diff"] = X_test["rsrp_serving_dbm"] - X_test["rsrp_neighbor_286_dbm"]

X_test.drop(columns=["rsrp_serving_dbm", "rsrp_neighbor_286_dbm"], inplace=True)

X_test.head()

X_eval = X_test.copy()

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

X_train.shape

Y_train.shape

Y_test.shape

X_test.shape

def plot_cm(Y_test, preds, Title):
  cm_rf = confusion_matrix(Y_test, preds)

  plt.figure(figsize=(6, 5))
  plt.imshow(cm_rf, interpolation='nearest', cmap=plt.cm.Blues)
  plt.title(f'Confusion Matrix - {Title}')
  plt.colorbar()
  tick_marks = np.arange(len(np.unique(Y_test)))
  plt.xticks(tick_marks, np.unique(Y_test), rotation=45)
  plt.yticks(tick_marks, np.unique(Y_test))
  thresh = cm_rf.max() / 2.
  for i in range(cm_rf.shape[0]):
      for j in range(cm_rf.shape[1]):
          plt.text(j, i, format(cm_rf[i, j], 'd'),
                  horizontalalignment="center",
                  color="white" if cm_rf[i, j] > thresh else "black")
  plt.ylabel('True label')
  plt.xlabel('Predicted label')
  plt.tight_layout()
  plt.show()

from sklearn.linear_model import LogisticRegression

logistic_model = LogisticRegression(solver='liblinear', random_state=43)
logistic_model.fit(X_train, Y_train)

"""## Training Evaluation"""

preds_train = logistic_model.predict(X_train)

print(classification_report(Y_train, preds_train))

plot_cm(Y_train, preds_train, "Logistic Model (Training)")

"""## Testing Evaluation"""

preds = logistic_model.predict(X_test)

print(classification_report(Y_test, preds))

plot_cm(Y_test, preds, "Logstic Model (Test)")

y_train_pred_proba = logistic_model.predict_proba(X_train)[:, 1]

fpr_train, tpr_train, thresholds_train = roc_curve(Y_train, y_train_pred_proba)

auc_score_train = roc_auc_score(Y_train, y_train_pred_proba)


y_pred_proba = logistic_model.predict_proba(X_test)[:, 1]


fpr, tpr, thresholds = roc_curve(Y_test, y_pred_proba)

auc_score = roc_auc_score(Y_test, y_pred_proba)


plt.figure(figsize=(8, 6))

plt.plot(fpr_train, tpr_train, color='green', lw=2, label=f'ROC curve (Train, AUC = {auc_score_train:.2f})')

plt.plot(fpr, tpr, color='blue', lw=2, label=f'ROC curve (Test, AUC = {auc_score:.2f})')

plt.plot([0, 1], [0, 1], color='red', lw=1, linestyle='--', label='Random Classifier')

plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve Comparison')
plt.legend(loc="lower right")
plt.grid(True)
plt.show()

logistic_model.intercept_

logistic_model.coef_

intercept = logistic_model.intercept_[0]
coef_1 = logistic_model.coef_[0][0]
coef_2 = logistic_model.coef_[0][1]

print(f"logit(mu | X) = {intercept:.2f} + ({coef_1:.2f} * sinr_serving_db) + ({coef_2:.2f} * rsrp_diff)")

X_eval["target"] = Y_test.values
X_eval["preds"] = logistic_model.predict(X_test)
print(X_eval[X_eval["preds"] == 1].shape)
print(X_eval[X_eval["target"] == 1].shape)
X_eval[(X_eval["preds"] == 1) & (X_eval["target"] == 1) ]

"""## Export Model to ONNX

We export a full Pipeline(StandardScaler -> LogisticRegression) so the ONNX
graph takes RAW engineered features ([sinr_serving_db, rsrp_diff]) and does the
scaling internally. This means consumers don't need to reproduce the scaler.
"""

from sklearn.pipeline import Pipeline
from skl2onnx import to_onnx

# Assemble a pipeline from the already-fitted scaler and model (no refit needed).
pipeline = Pipeline([("scaler", scaler), ("model", logistic_model)])

# Unscaled engineered features, in the order the scaler was fit on.
feature_names = ["sinr_serving_db", "rsrp_diff"]
X_raw = X_eval[feature_names].to_numpy()

# Use a float32 sample as the input prototype for the ONNX graph.
onnx_model = to_onnx(
    pipeline,
    X_raw[:1].astype(np.float32),
)

with open("nr_rsrp_sinr_logistic.onnx", "wb") as f:
    f.write(onnx_model.SerializeToString())

print(f"Saved ONNX pipeline (scaler + model) with input features "
      f"{feature_names} to nr_rsrp_sinr_logistic.onnx")

# Verify the ONNX pipeline reproduces the sklearn pipeline predictions on raw input.
import onnxruntime as ort

sess = ort.InferenceSession("nr_rsrp_sinr_logistic.onnx")
input_name = sess.get_inputs()[0].name
onnx_preds = sess.run(None, {input_name: X_raw.astype(np.float32)})[0]

print("Predictions match sklearn pipeline:",
      np.array_equal(onnx_preds.ravel(), pipeline.predict(X_raw)))

